### ISSUE TITLE
RequestError when trying to publish

### ISSUE THREAD

**Issue by ballaneypranav** [Virginia-iGEM/igem-wikibrick#11]
Hi, I've generated the template using generator-igemwiki, and it is `serve`d perfectly, but `push:files` and `publish` tasks fail with the following error, right after I enter the password:

```
Try running gulp publish again.
Unhandled rejection RequestError: Error: write EPROTO 140069834409856:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1942:

    at new RequestError (/home/pranav/code/igem-wiki/igem-2020-wiki/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/pranav/code/igem-wiki/igem-2020-wiki/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/pranav/code/igem-wiki/igem-2020-wiki/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/pranav/code/igem-wiki/igem-2020-wiki/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.onRequestError (/home/pranav/code/igem-wiki/igem-2020-wiki/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:424:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7

[19:51:34] The following tasks did not complete: publish, push:files
[19:51:34] Did you forget to signal async completion?
```

Could you please look into it?
Let me know if I need to provide any additional information.

**Comment by Mantissa-23** [comment]
Hi, this is most likely because iGEM recently migrated to HTTPS, whereas previously they were using HTTP. Luckily I can still test this because it isn't an issue lying somewhere beyond login. I can probably take a look this weekend.

**Comment by ballaneypranav** [comment]
Yeah, I tried changing the submit URL in igemwiki-api/lib/constants.js to the https version, but that didn't work. The gulp.json file for igem-wikibrick has nodeflags too, and I have a feeling it is related to that.

Firstly, [gulp.json](https://github.com/Virginia-iGEM/igem-wikibrick/blob/master/gulp.json) doesn't have quotes around keys and values, and my IDE complains about that. But secondly and more importantly, I can't find where gulpfile.js is linked to gulp.json. I found an article [here](https://medium.com/@jh3y/how-to-parsing-a-config-file-for-custom-builds-with-gulp-js-3af364ffea30) about how to achieve this, but I don't see any similar require statements in gulpfile.js in igem-wikibrick. 

This is my first time working with gulp, so I'm probably missing something. Just thought I'd point it out here to give you some pointers.

Thanks a lot for taking a look.

**Comment by Mantissa-23** [comment]
Apologies on taking so long getting to this! This error just keeps popping up. I wish iGEM would upgrade their SSL to TLSv1.3+, that would resolve all these issues and make their website far more secure.

The fix: Add the following line to your `gulpfile.js`, anywhere near the top with the other `require` statement:

```js
require('tls').DEFAULT_MIN_VERSION = 'TLSv1'
```

I'm updating `igem-wikibrick` and `generator-igemwiki` with these, so any future users should not have this issue. Hopefully once and for all.

**Comment by Mantissa-23** [comment]
Let me know if this works for you. I'll reopen this if you're still having issues.
