### ISSUE TITLE
gulp publish fails intermittently

### ISSUE THREAD

**Issue by serenahacker** [Virginia-iGEM/igem-wikibrick#14]
When I run 'gulp publish -l', I see some files upload successfully, but then I see this error: 
```
Upload failed, retrying upload...

Retry count exceeded.

Unhandled rejection Error: Upload failed

    at /Users/serenahacker/Desktop/iGEM/wiki2020/node_modules/igemwiki-api/lib/upload.js:110:13

    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[23:10:33] The following tasks did not complete: publish, push:files

[23:10:33] Did you forget to signal async completion?
```
When I upload my files in smaller batches, it is more frequently successful.

**Comment by Mantissa-23** [comment]
I just realized I completely missed this, and the wiki deadline passed. Were you guys still able to get your wiki uploaded successfully?

Not that my answer would have helped you much - you just have to keep retrying. Increasing the retry count in the config.js file helps. This happens because iGEM uses a single server to host all of the wikis, and the closer you get to the wiki deadline, the more often the server just doesn't get to or completely rejects requests.

Apologies about that, been busy with work.
